# Generated by Django 4.2.23 on 2025-09-01 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 12, 14, 43, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
