# Generated by Django 4.2.23 on 2025-08-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
