# Generated by Django 4.2.23 on 2025-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'get_latest_by': 'created_date'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
